name: run tests and linters

on: push

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: linter
        uses: golangci/golangci-lint-action@v3
        with: 
          version: v1.50.1

  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: make test
        run: make test